### ISSUE TITLE
OH1 - Research: Create and manage an account

### ISSUE THREAD

**Issue by daylesalmon** [wmcadigital/wmn-sprints#10]
🗂 **Project ID:** OH
📝 **Story No:** 1
🚩 **Priority:** 
***

**Epic:**
User needs just one account to use all WMN services.
 
Working with the Single View of Customer & Data project teams to create the best user journey for one single account

***
<details>
<summary>Story details</summary>
<br/>

✏️ **Design Size:** 0/1/2/3/5/8/13/20/40/100/♾/❓/☕️
⌨️ **Dev Size:** 0/1/2/3/5/8/13/20/40/100/♾/❓/☕️

**Assigned to:**

***
#### As a 
Leisure, Commuter, Business

#### I need to
have simple access to different WMN services

#### In order to
I can use them easily
***

#### Acceptance criteria
Can I...?
- [ ] Account discovery; decision on identity management

</details>

***

**Comment by mrmjprice** [comment]
@KaterinaKir Is this also #61?

**Comment by KaterinaKir** [comment]
I closed this issue and updated #61
