### ISSUE TITLE
P14.4 - See full route of tram stops on a map and list

### ISSUE THREAD

**Issue by somtmee** [wmcadigital/wmn-sprints#109]
**Epic:** Users want to know if the service stops at their stop
***

#### As a
person who is travelling by a tram service for the first time

#### I need to
to see each station on tram service route

#### So that
I know where the tram is going

***
### Acceptance criteria
- [x] Use can see full route of tramstations in a list
- [x] User can see the direction of travel (final destination) of the tram

***

**Comment by jkmnch** [comment]
Story split into Bus and Tram since Bus route map plotting has API issues. Bus route map story has been added to the backlog: #126
