### ISSUE TITLE
DA.1 - Choose quiet hours

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-sprints#122]
**Epic:** What's the big picture?
Users want to choose quiet hours so they are not disturbed with disruptions alerts.
#### As a
User

#### I need to
choose when I want to get alerts

#### So that
I'm not disturbed when I'm not travelling

***
### Acceptance criteria
- [x] Users can set quiet hours and days for disruptions when signing up.
- [x] Users can set quiet hours and days on their alerts dashboard.
- [ ] Back-end work is completed for go live

***
[Link to repo - wmn-disruption-manage](https://github.com/wmcadigital/wmn-disruption-manage)
***

**Comment by jkmnch** [comment]
## Prototypes in Figma

### [Desktop](https://www.figma.com/proto/0tLPvD9FakaEJApYNIrKvT/Disruption-Alerts-Choose-Quiet-Hours?page-id=0%3A1&node-id=47%3A3598&viewport=241%2C48%2C0.33&scaling=scale-down&starting-point-node-id=12%3A648)

### [Mobile](https://www.figma.com/proto/0tLPvD9FakaEJApYNIrKvT/Disruption-Alerts-Choose-Quiet-Hours?page-id=12%3A2552&node-id=12%3A2553&viewport=241%2C48%2C0.24&scaling=scale-down&starting-point-node-id=12%3A2553)

**[Figma file link](https://www.figma.com/file/0tLPvD9FakaEJApYNIrKvT/Disruption-Alerts-Choose-Quiet-Hours?node-id=0%3A1)**
