### ISSUE TITLE
CS.1 - Customer services through live chat

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-sprints#123]
**Epic:** What's the big picture?
Provide live chat support for customers
***
#### As a
TfWM customer

#### I need to
resolve my issue quickly

#### So that
I can continue using public transport

***
### Acceptance criteria
- [x] Write scripts (questions we ask before user is connected to an agent)
- [x] Make a list of pages where access to live chat should sit (e.g pages where we get the most enquiries)
- [x] Customise live chat design in line with TfWM design system (8by8)
- [x] Live chat supplier has been procured by customer services team (Lee to get quotes and get it signed off)
- [x] Review live chat solution to make sure it complies with WCAG 2.1 AA (contact supplier to check)
- [x] Live chat supplier will share a code that a developer will add to our website
- [x] Add live chat to the existing contact us component in Umbraco

***

**Comment by jkmnch** [comment]
Update 11/11 - Lee C. confirmed that the live chat project could be shelved because of capacity OR just delayed for 7-8 weeks. Sales order has still not been signed off by Sarah Jones.
