### ISSUE TITLE
TK5.1 - Corporate Ticketing Research

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmn-sprints#130]
**Epic:** TBC

***
We need to scope the requirements with Warren and his team to understand what we need to deliver.

***
### Acceptance criteria
- [x] Gather research and business requirements from stakeholders
- [x] Gather user needs from businesses and employees
- [x] Present findings to stakeholders
- [x] Scope requirements from user needs and business objectives

***

**Comment by jkmnch** [comment]
This discovery is delayed due to limited Swift resources.
