### ISSUE TITLE
P14.12.3 - Fix bus stop API issues

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmn-sprints#209]
@mushtaque12 has caught some issues with the bus route API that has been developed that need resolving

**Comment by sudheer-rk** [comment]
Had a meeting with Jonathan Myers and Mushtaque to resolve issues with service_id and route_id on the new api created by Mark. JM discussed a way to retrieve service id from another api and also suggested replacing the journey planner API with https://api.wmnetwork.co.uk/. Mushtaque is working on this issue now.

**Comment by sam-wmca** [comment]
Closed as this is a duplicate of #193
