### ISSUE TITLE
OH4.3 - Header and footer navigation

### ISSUE THREAD

**Issue by daylesalmon** [wmcadigital/wmn-sprints#25]
***

🗂 **Project ID:** OH4
📝 **Story No:** 3
🚩 **Priority:** M
***

**Epic:** Primary navigation for header and footer

***
<details>
<summary>Story details</summary>
<br/>

✏️ **Design Size:** 13
⌨️ **Dev Size:** 20

**Assigned to:**

***
#### As a
user

#### I need to
navigate between the BETA and old website using the same header and footer

#### In order to
navigate the website

***

#### Acceptance criteria
- [x] Design completed
- [x] User testing completed
- [ ] CMS editor can manage links in the header and footer using Umbraco (does not follow site folder structure)
- [ ] Header and footer only editable by a specific group of content editors
- [ ] Header available on new Umbraco
- [ ] Header ready to be deployed on old Umbraco
- [ ] Footer available on new Umbraco
- [ ] Footer ready to be deployed on old Umbraco
- [ ] New primary nav is rolled out

</details>

***

**Comment by mrmjprice** [comment]
https://github.com/wmcadigital/wmn-design-system/issues/366

https://github.com/wmcadigital/wmn-design-system/issues/367
