### ISSUE TITLE
OH4.2.2 - Service feedback survey

### ISSUE THREAD

**Issue by daylesalmon** [wmcadigital/wmn-sprints#26]
***

🗂 **Project ID:** OH4
📝 **Story No:** 2.2
🚩 **Priority:** S
***

**Epic:** Users should be able to give feedback about services so we can make reactive changes

***
<details>
<summary>Story details</summary>
<br/>

✏️ **Design Size:** 5
⌨️ **Dev Size:** 8

**Assigned to:**

***
#### As a
user

#### I need to
give feedback about a service

#### In order to
tell the service delivery team any pain points or improvements

***

#### Acceptance criteria
Does the survey...?
- [x] design completed
- [ ] exist
- [ ] answer fields validate
- [ ] URL allow for the service name to be passed through e.g. ?service=serviceName
- [ ] submit to an API
- [ ] data is received by the API

Design 
https://app.zeplin.io/project/5f3a31b783dbdf7ca550b073/screen/5f438e8dfb912a33a909a2be 

</details>

***

**Comment by KaterinaKir** [comment]
De-prioritised due to Hotjar available. Will pick up if we have downtime.
