### ISSUE TITLE
OH4.10 - Warning when system is down

### ISSUE THREAD

**Issue by daylesalmon** [wmcadigital/wmn-sprints#32]
***

🗂 **Project ID:** OH4
📝 **Story No:** 10
🚩 **Priority:** C
***
**Epic:** Editors should be able to tell users when system is down

***

<summary>Story details</summary>
<br/>

✏️ **Design Size:** 0/1/2/3/5/8/13/20/40/100/♾/❓/☕️
⌨️ **Dev Size:** 0/1/2/3/5/8/13/20/40/100/♾/❓/☕️

***
#### As a
CMS editor

#### I need to
tell users when a system is down

#### So
 II can stop users from trying to use that channel for contacting WMCA

***
#### Acceptance criteria

- [x]  Editor can create multiple contact detail blocks  
- [x] Editor can use contact detail blocks within content pages 
- [x] Editor has to change settings in one place
- [x] Editor can edit address 
- [x] Editor can edit email address 
- [x] Editor can edit phone number 
- [x] Editor can edit opening times 
- [x] Editor can edit social media handles 
- [x] Editor can add an error info message 
- [ ] Could have: editor can set automatic reversion time or date

**Comment by KaterinaKir** [comment]
This is completed.
