### ISSUE TITLE
RP2. Receive acknowledgment about my anti-social behaviour report

### ISSUE THREAD

**Issue by daylesalmon** [wmcadigital/wmn-sprints#4]
🗂 **Project ID:** RP
📝 **Story No:** 2
🚩 **Priority:** 
***

**Epic:**
Improve safer travel user experience by receiving confirmation email when I submit incident report

***
<details>
<summary>Story details</summary>
<br/>

✏️ **Design Size:** 0/1/2/3/5/8/13/20/40/100/♾/❓/☕️
⌨️ **Dev Size:** 0/1/2/3/5/8/13/20/40/100/♾/❓/☕️

**Assigned to:**

***
#### As a 
Leisure/Commuter/Business

#### I need to
be sure that my incident report has been submitted

#### In order to
know that safer travel police has been informed and will respond accordingly

***

#### Acceptance criteria
Can I...?
- [ ] receive confirmation email 
- [ ] do I understand what confirmation email says

</details>

**Comment by mrmjprice** [comment]
SaferTravel is going to remain on their website.
