### ISSUE TITLE
PM.1 - Review and plan for Phase 2B

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-sprints#63]
**Epic:** Define what will be delivered in Phase 2B

***
#### As a
manager/ delivery team

#### I need to
know what will be delivered during Phase 2B

#### So that
we can plan for next year

***
### Acceptance criteria
- [x] Check whether all backlog items are still relevant for the business
- [x] Check whether there are new business and user needs
- [x] Sign off Phase 2B backlog and present to the working group

***

**Comment by mrmjprice** [comment]
Asked for a discussion at December Programme board to seek clarification on scope.

**Comment by mrmjprice** [comment]
Putting this as complete because we've done that work.

Should something additional come along, I'll create a new item.
