### ISSUE TITLE
UR.7 - SMS Trial Report 

### ISSUE THREAD

**Issue by somtmee** [wmcadigital/wmn-sprints#66]
**Epic:** Compile data for the SMS Trial and produce a fortnightly report to inform stakeholders of progress against trial KPIs and objectives

***
#### As a
stakeholder in the SMS Trial project

#### I need to
know how the trial is performing against its objectives

#### So that
I can determine if the trial has been a success

***
### Acceptance criteria
- [x] Retrieve latest 'to-date' data on SMS trial (sign, ups, messages sent, survey feedback) 
- [x] Put data into a report
- [x] Share data every fortnight in email update and show and tell
- [x] Share report as Word doc to RTCC stakeholders
- [x] Analyse high drop out rate
***

**Comment by mrmjprice** [comment]
Closed because we're now doing this routinely.
