### ISSUE TITLE
TI 3.2 Learn about adopting new working practices to help the transport network

### ISSUE THREAD

**Issue by daylesalmon** [wmcadigital/wmn-sprints#7]
🗂 **Project ID:** TI
📝 **Story No:** 3.2
🚩 **Priority:** 
***

**Epic:**

***
<details>
<summary>Story details</summary>
<br/>

✏️ **Design Size:** 0/1/2/3/5/8/13/20/40/100/♾/❓/☕️
⌨️ **Dev Size:** 0/1/2/3/5/8/13/20/40/100/♾/❓/☕️

**Assigned to:**

***
#### As a 
Leisure/Commuter/Business

#### I need to
find out transport advise on new working practices

#### In order to
help me avoid congestion, disruption and travel around network easily
***

#### Acceptance criteria
Can I...?
- [ ] find new working practices
- [ ] do I understand new working practices

</details>

***

**Comment by KaterinaKir** [comment]
No longer required.
