### ISSUE TITLE
TK3.10 - Operator-specific ticket - Introduction and mode selection

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-sprints#77]
**Epic:** Building an operator-specific ticket for my needs

***
#### As a
person choosing an operator-specific ticket

#### I need to
understand what an operator-specific ticket is

#### So that
I buy a ticket that meets my needs

***
### Acceptance criteria
- [x] Plain English description of what an operator-specific ticket is
- [ ] User can see product introduction/marketing information
- [ ] User can follow a link to book train tickets on another website
- [x] User can choose if their ticket covers bus, tram or both
- [x] User can see modal icons
- [ ] There is a text alternative of modal icons for screenreaders

***

**Comment by KaterinaKir** [comment]
Closed. No longer relevant.
