### ISSUE TITLE
TK3.13 - Structured data and SEO

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-sprints#80]
**Epic:** Machine-readable data 

***
#### As a
Search engine/machine

#### I need to
have the ticket data in a structured format

#### So that
I can help users get to the information quickly

***
### Acceptance criteria
- [x] Each ticket summary page has [structured data](https://schema.org) about the customisations of the ticket
- [x] Each ticket product page has [structured data](https://schema.org) about the overview
- [x] Dynamic title based on product name
- [x] Dynamic description based on product description
- [x] where an nTicket shows the 'n' as an icon, it should show as nTicket still in a search engine result
- [x] Tags (need to be defined)
- [x] Dynamic meta/social image based on modes covered by ticket

***

**Comment by KaterinaKir** [comment]
@houbly please read documentation here https://developers.google.com/search/docs/advanced/structured-data/intro-structured-data
