### ISSUE TITLE
TK3.15 - Ticket summary page - ticket formats and sales channel

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-sprints#82]
**Epic:** What's the big picture?

***
#### As a
person who has chosen a ticket and duration

#### I need to
see the formats of a ticket, where to buy the ticket from and buy if online

#### So that
I can buy the right ticket

***
### Acceptance criteria
- [x] User can see all the possible formats for their ticket (e.g. Swift card; paper ticket; app purchase; Swift on Mobile)
- [x] User can see all the possible sales channels for their ticket (e.g. Online, offline, mobility credits)
- [x] If a sales channel is cheaper (e.g. is on sale), highlight this sales channel
- [x] If a sales channel is cheaper (e.g. is on sale), all channels show the price
- [x] If the user started their journey in the Swift SSP to add a ticket to an existing Swift card, their Swift card should appear as a sales channel
- [x] If the ticket can be bought online, the user can continue the sales journey
- [x] If the ticket can be bought offline, show all offline sales channels (e.g. Swift kiosk; Bus driver; West Midlands Network travel information centre; National Express travel shop; train station ticket office; train station ticket machine; tram ticket machine)
- [x] Could have: See how to ask for that ticket: "Ask for a [ticketName]"

***
More info: 
Ticket summary page Desktop:
https://www.sketch.com/s/2d569680-ef84-438f-ae8b-69f0c6f5462a/a/l1zlYKv 

Ticket summary page mobile: 
https://www.sketch.com/s/2d569680-ef84-438f-ae8b-69f0c6f5462a/v/4m94nJ/a/R1VxeM8/r/JPMoMe

Discount UI:
https://www.figma.com/file/sTE7BlnIqGFUrlxeuzKav0/Ticket-Finder-Duration-Discount?node-id=0%3A1

Price:
Show price for each fulfilment option. If one fulfilment option is cheaper, show tag 'cheapest'. And say 'From £XX' in the body section under ticket name.  

Hierarchy
When users lands on a ticket summary page on the website (web browser);
* 1st By online 
* 2nd Buy through app. If user doesn’t have an app they would need to download it. Can we detect whether user is on android or apple device so we don't show two CTA buttons on mobile view?
* 3rd Buy in person. Since user cannot do this online, this is the last option. 

When users lands on a ticket summary page on the One app.
* Only one option will be available - buy through One app. 
* Link to browser (WMN) website should be available only in that case where user cannot buy the ticket from the app. Buy on other apps will be available if user cannot buy it on Swift app. 

We need extra retail points added in as fields into the CRM so we can show relevant apps. Swift to advise where we can get this data from.

**Comment by jkmnch** [comment]
Here are the ticket summary designs if a sales channel is cheaper: https://zpl.io/aR4l1nv

If a sales channel is cheaper than others, we'll highlight that channel using the 'Cheaper' tag. We'll also show the prices for all sales channels only if one channel is cheaper than the others, so users can see the difference.
