### ISSUE TITLE
TK3.16 - Transactional emails when a new Swift card has been created by Euclid

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-sprints#83]
**Epic:** What's the big picture?

***
#### As a
person who will receive a new Swift card

#### I need to
know when my Swift card has been posted

#### So that
I can be confident I will receive my Swift card soon to travel with

***
### Acceptance criteria
- [ ] **We need to user test to see if this could be one email or needs to be two**
- [ ] Transactional email (Email 1) is triggered in Campaign Monitor when a user's Swift card has been created
- [ ] Transactional email (Email 2) is triggered for 9am the next day after a user's Swift card has been created

#### Email 1
- [ ] User knows their Swift card has been made and will be posted shortly (some possible pushback about this because we only know the card has been made, not that it's in the post)
- [ ] User knows who to contact for help

#### Email 2
- [ ] User knows how to use their Swift card
- [ ] If the card is PAYG, the user knows how to collect to their Swift card

***

**Comment by KaterinaKir** [comment]
This task is closed. Swift team will review email communication.
