### ISSUE TITLE
OH4.14 - Journey planner Umbraco widget

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-sprints#94]
Restyle the existing Umbraco widget so devs can add it to new Umbraco.

<img width="340" alt="Screenshot 2021-03-01 at 08 37 46" src="https://user-images.githubusercontent.com/10854265/109471942-6899d980-7a69-11eb-9079-46dad1fb4ad5.png">

Add to Design System so other companies can use it.

**Comment by jkmnch** [comment]
Link to restyled designs in Zeplin: https://zpl.io/V1EwnoZ

**Comment by KaterinaKir** [comment]
Catia is integrating with JP API. HTML is done. Awaiting API key.
