### ISSUE TITLE
DS6.1 - Bus autocomplete API (without disruptions)

### ISSUE THREAD

**Issue by daylesalmon** [wmcadigital/wmn-sprints#96]
**Epic:** What's the big picture?

***
#### As a
Developer

#### I need to
be able to hit the bus autocomplete without disruption data

#### So that
The bus autocomplete feed loads faster when disruptions data isn't needed

***
### Acceptance criteria
- [ ] Bus autocomplete API: https://api.wmnetwork.co.uk/bus/v1/service?q=77 has an additional param that lets developers hit it without disruption data for example it could be https://api.wmnetwork.co.uk/bus/v1/service?q=77?noDisruptions=true
- [x] The API returns results without disruptions and direction data, for example 
{
  "disruptionTimeWindow": {
    &nbsp;&nbsp;"start": "2021-03-01T08:42:17",
    &nbsp;&nbsp;"end": "2021-03-01T14:52:17"
  },
  "services": [
    {
      &nbsp;&nbsp;"id": "10154",
      &nbsp;&nbsp;"mode": "bus",
      &nbsp;&nbsp;"serviceNumber": "77",
      &nbsp;&nbsp;~~"hasDisruptions": false,
      &nbsp;&nbsp;"disruptionSeverity": "none",~~
      &nbsp;&nbsp;"routes": [
       &nbsp;&nbsp;&nbsp; {
         &nbsp;&nbsp;&nbsp; ~~"direction": "inbound",~~
         &nbsp;&nbsp;&nbsp;"operatorCode": "NXB",
         &nbsp; &nbsp;&nbsp;"routeName": "Sutton Coldfield - Walsall via Streetly",
         &nbsp; &nbsp;&nbsp;~~"hasDisruption": false,
         &nbsp;&nbsp;&nbsp;"disruptionSeverity": "none"~~
        },
         ...
    ]
}

- [x] The API loads much quicker as there is no disruption data attached to it

***

**Comment by Rippled** [comment]
done
